version: 0.0.{build}-ci
image: Visual Studio 2017
init:
- ps: >-
    $tagRelease = $env:APPVEYOR_REPO_TAG -eq 'true'

    if ($tagRelease) {
      $tag = $env:APPVEYOR_REPO_TAG_NAME
      Update-AppveyorBuild -Version "$tag"
    }
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
install:
- cmd: >-
    REM This needs to be under CMD - git writes to success messages to standard error for some reason...

    git submodule update --init --recursive
build_script:
- ps: >-
    dotnet build

    dotnet pack
artifacts:
- path: '**/*.nupkg'